"""
ISO 27001:2022 Knowledge Base
Contains comprehensive information about the standard for the auditor agent
"""

# ISO 27001:2022 knowledge base
ISO_27001_KNOWLEDGE = {
    "overview": """
    ISO 27001:2022 is an international standard for Information Security Management Systems (ISMS).
    It provides a framework for establishing, implementing, maintaining, and continually improving
    information security within an organization.
    
    Key changes in the 2022 version:
    - Reduced from 114 controls to 93 controls
    - Reorganized into 4 control groups instead of 14
    - New controls for cloud security, threat intelligence, and data leakage prevention
    """,
    
    "control_groups": {
        "people": "Controls related to human resources, awareness, and training",
        "organizational": "Controls for policies, procedures, and organizational structure",
        "technological": "Technical controls for systems and infrastructure",
        "physical": "Physical security controls for facilities and equipment"
    },
    
    "key_controls": {
        "A.5.1": "Information security policies",
        "A.5.2": "Information security roles and responsibilities",
        "A.5.3": "Segregation of duties",
        "A.5.4": "Management responsibilities",
        "A.5.5": "Contact with authorities",
        "A.5.6": "Contact with special interest groups",
        "A.5.7": "Threat intelligence",
        "A.5.8": "Information security risk assessment",
        "A.5.9": "Information security risk treatment",
        "A.6.1": "Internal organization",
        "A.6.2": "Mobile device policy",
        "A.6.3": "Information security event reporting",
        "A.6.4": "Information security events assessment",
        "A.6.5": "Incident response",
        "A.6.6": "Learning from information security incidents",
        "A.6.7": "Evidence collection",
        "A.6.8": "Business continuity",
        "A.6.9": "Business continuity planning and testing",
        "A.7.1": "Screening",
        "A.7.2": "Terms and conditions of employment",
        "A.7.3": "Information security awareness, education and training",
        "A.7.4": "Disciplinary process",
        "A.7.5": "Information security event reporting",
        "A.7.6": "Information security event assessment",
        "A.7.7": "Incident response",
        "A.7.8": "Learning from information security incidents",
        "A.7.9": "Evidence collection",
        "A.7.10": "Business continuity",
        "A.7.11": "Business continuity planning and testing",
        "A.8.1": "Inventory of information and other associated assets",
        "A.8.2": "Ownership of assets",
        "A.8.3": "Acceptable use of assets",
        "A.8.4": "Return of assets",
        "A.8.5": "Classification of information",
        "A.8.6": "Labelling of information",
        "A.8.7": "Handling of assets",
        "A.8.8": "Media handling",
        "A.8.9": "Physical media transfer",
        "A.8.10": "Disposal of media",
        "A.8.11": "Business continuity",
        "A.8.12": "Business continuity planning and testing",
        "A.8.13": "Information security event reporting",
        "A.8.14": "Information security event assessment",
        "A.8.15": "Incident response",
        "A.8.16": "Learning from information security incidents",
        "A.8.17": "Evidence collection",
        "A.8.18": "Business continuity",
        "A.8.19": "Business continuity planning and testing",
        "A.8.20": "Information security event reporting",
        "A.8.21": "Information security event assessment",
        "A.8.22": "Incident response",
        "A.8.23": "Learning from information security incidents",
        "A.8.24": "Evidence collection",
        "A.8.25": "Business continuity",
        "A.8.26": "Business continuity planning and testing",
        "A.8.27": "Information security event reporting",
        "A.8.28": "Information security event assessment",
        "A.8.29": "Incident response",
        "A.8.30": "Learning from information security incidents",
        "A.8.31": "Evidence collection",
        "A.8.32": "Business continuity",
        "A.8.33": "Business continuity planning and testing",
        "A.8.34": "Information security event reporting",
        "A.8.35": "Information security event assessment",
        "A.8.36": "Incident response",
        "A.8.37": "Learning from information security incidents",
        "A.8.38": "Evidence collection",
        "A.8.39": "Business continuity",
        "A.8.40": "Business continuity planning and testing",
        "A.8.41": "Information security event reporting",
        "A.8.42": "Information security event assessment",
        "A.8.43": "Incident response",
        "A.8.44": "Learning from information security incidents",
        "A.8.45": "Evidence collection",
        "A.8.46": "Business continuity",
        "A.8.47": "Business continuity planning and testing",
        "A.8.48": "Information security event reporting",
        "A.8.49": "Information security event assessment",
        "A.8.50": "Incident response",
        "A.8.51": "Learning from information security incidents",
        "A.8.52": "Evidence collection",
        "A.8.53": "Business continuity",
        "A.8.54": "Business continuity planning and testing",
        "A.8.55": "Information security event reporting",
        "A.8.56": "Information security event assessment",
        "A.8.57": "Incident response",
        "A.8.58": "Learning from information security incidents",
        "A.8.59": "Evidence collection",
        "A.8.60": "Business continuity",
        "A.8.61": "Business continuity planning and testing",
        "A.8.62": "Information security event reporting",
        "A.8.63": "Information security event assessment",
        "A.8.64": "Incident response",
        "A.8.65": "Learning from information security incidents",
        "A.8.66": "Evidence collection",
        "A.8.67": "Business continuity",
        "A.8.68": "Business continuity planning and testing",
        "A.8.69": "Information security event reporting",
        "A.8.70": "Information security event assessment",
        "A.8.71": "Incident response",
        "A.8.72": "Learning from information security incidents",
        "A.8.73": "Evidence collection",
        "A.8.74": "Business continuity",
        "A.8.75": "Business continuity planning and testing",
        "A.8.76": "Information security event reporting",
        "A.8.77": "Information security event assessment",
        "A.8.78": "Incident response",
        "A.8.79": "Learning from information security incidents",
        "A.8.80": "Evidence collection",
        "A.8.81": "Business continuity",
        "A.8.82": "Business continuity planning and testing",
        "A.8.83": "Information security event reporting",
        "A.8.84": "Information security event assessment",
        "A.8.85": "Incident response",
        "A.8.86": "Learning from information security incidents",
        "A.8.87": "Evidence collection",
        "A.8.88": "Business continuity",
        "A.8.89": "Business continuity planning and testing",
        "A.8.90": "Information security event reporting",
        "A.8.91": "Information security event assessment",
        "A.8.92": "Incident response",
        "A.8.93": "Learning from information security incidents"
    },
    
    "implementation_steps": [
        "1. Establish the context of the organization",
        "2. Define the scope of the ISMS",
        "3. Conduct risk assessment",
        "4. Select and implement controls",
        "5. Monitor and review performance",
        "6. Continual improvement"
    ],
    
    "benefits": [
        "Enhanced security posture",
        "Regulatory compliance",
        "Customer trust and confidence",
        "Risk reduction",
        "Business continuity",
        "Competitive advantage"
    ]
}
